import Link from "next/link";
import type { Metadata } from "next";
import { Card } from "@/components/ui";

export const metadata: Metadata = {
  title: "How to use MarketMath",
  description:
    "Core concepts in plain language, then three worked workflows: judging one company, finding ideas, and comparing peers.",
};

function Concept({
  name,
  slug,
  children,
}: {
  name: string;
  slug?: string;
  children: React.ReactNode;
}) {
  return (
    <div className="py-3">
      <p className="text-sm font-semibold">
        {name}
        {slug && (
          <Link
            href={`/learn/metric/${slug}`}
            className="ml-2 text-xs font-normal text-accent hover:underline underline-offset-2"
          >
            full reference →
          </Link>
        )}
      </p>
      <p className="text-sm text-muted mt-1 leading-relaxed">{children}</p>
    </div>
  );
}

function Step({ n, title, children }: { n: number; title: string; children: React.ReactNode }) {
  return (
    <div className="flex gap-4">
      <div className="shrink-0 w-7 h-7 rounded-full bg-foreground text-white grid place-items-center text-xs font-semibold mt-0.5">
        {n}
      </div>
      <div className="min-w-0">
        <p className="text-sm font-semibold">{title}</p>
        <div className="text-sm text-muted mt-1 leading-relaxed space-y-2">{children}</div>
      </div>
    </div>
  );
}

export default function HowToUsePage() {
  return (
    <div className="py-8 max-w-3xl">
      <p className="text-xs text-faint">
        <Link href="/learn" className="hover:text-foreground">Learn</Link> / How to use
      </p>
      <h1 className="text-2xl font-semibold tracking-tight mt-1">How to use MarketMath</h1>
      <p className="text-sm text-muted mt-2 leading-relaxed">
        The site answers three questions about any company: <em>is the business good,
        is the price reasonable, and what would have to be true for a buyer to do
        well?</em> This page gives you the minimum concepts, then three concrete
        workflows using live pages.
      </p>

      {/* Concepts */}
      <h2 className="text-base font-semibold tracking-tight mt-10">The six concepts that carry everything</h2>
      <Card className="mt-3 px-5 divide-y divide-border">
        <Concept name="CAGR — compound annual growth rate" slug="revenue-cagr">
          The single growth number that summarizes a multi-year change: the constant
          yearly rate that turns the starting value into the ending value. If revenue
          went from $100B to $161B in five years, the CAGR is 10% — because
          $100B × 1.10⁵ ≈ $161B. We show CAGRs over 3, 5, 10 and 15 years so you can
          see whether growth is durable or a recent spurt. One good year is noise; a
          10-year CAGR is a track record.
        </Concept>
        <Concept name="Free cash flow (FCF)" slug="fcf-yield">
          Cash generated by operations minus capital spending — the money that&apos;s
          actually left over for owners after running and maintaining the business.
          Earnings can be shaped by accounting; cash is harder to fake. Most valuation
          on this site is anchored to FCF. Caveat: banks and insurers report cash flow
          differently, so FCF-based metrics show “—” for them.
        </Concept>
        <Concept name="Yields — the price tag, inverted" slug="fcf-yield">
          FCF yield = FCF ÷ market cap. It restates the price as “what return would I
          earn if the business never grew?” A 5% FCF yield competes directly with a
          bond; a 1.5% FCF yield means most of your return must come from future
          growth. Shareholder yield adds dividends + buybacks: what the company
          actually hands back each year.
        </Concept>
        <Concept name="DCF — discounted cash flow" slug="implied-fcf-growth">
          The value of a business is all its future cash, discounted back to today
          (cash next decade is worth less than cash now). A DCF takes a growth
          assumption and produces a value. The problem: tiny assumption changes swing
          the answer wildly. That&apos;s why the site leans on the reverse version.
        </Concept>
        <Concept name="Reverse DCF — reading expectations out of the price" slug="implied-fcf-growth">
          Instead of guessing growth to get a value, start from the market cap and
          solve for the growth that would justify it. Now you have a testable claim:
          “this price needs 19% FCF growth for a decade.” Compare that to what the
          company has actually done. You don&apos;t need to predict the future —
          only to judge whether the embedded assumption is plausible.
        </Concept>
        <Concept name="Quality score and red flags" slug="quality-score">
          A 0–100 composite of profitability, growth, consistency, balance-sheet
          strength, and capital discipline — with every weight documented. Red flags
          are mechanical threshold checks (revenue shrinking, dilution, debt over 5
          years of FCF…). Neither is a verdict; they tell you where to look before
          you commit money or move on.
        </Concept>
      </Card>

      {/* Workflow 1 */}
      <h2 className="text-base font-semibold tracking-tight mt-12">
        Workflow 1 — Judge one company in ten minutes
      </h2>
      <p className="text-sm text-muted mt-1">
        Example: open <Link href="/company/COST" className="text-accent hover:underline">COST</Link>{" "}
        (Costco) and read the page top to bottom — it&apos;s ordered as an argument.
      </p>
      <Card className="mt-3 p-5 space-y-5">
        <Step n={1} title="Header: what kind of company is this?">
          <p>
            The badges classify it (Peter Lynch style: slow grower / stalwart / fast
            grower) and score its quality. A “Stalwart · Quality: High” with zero red
            flags reads very differently from a “Fast grower · Quality: Low” with
            four.
          </p>
        </Step>
        <Step n={2} title="“What today's price assumes” — the expectations check">
          <p>
            This is the reverse DCF in one sentence. If it says the price assumes 12%
            FCF growth and history delivered 13%, you&apos;re paying for a repeat of
            the past — reasonable. If it assumes 19% and history is 8%, the price
            needs acceleration that hasn&apos;t happened yet. That gap is the whole
            investment question.
          </p>
        </Step>
        <Step n={3} title="Growth record + fundamentals charts: is the machine real?">
          <p>
            Look for bars that climb steadily (revenue, net income, FCF) and one that
            falls: diluted shares. A falling share count means every remaining share
            owns more of the business. Choppy or flat bars → the growth story is
            weaker than the narrative.
          </p>
        </Step>
        <Step n={4} title="Track record: did owners actually get paid?">
          <p>
            The $100-vs-SPY cards answer “would I have beaten the index just holding
            this?” The $1 test asks Buffett&apos;s question: did each dollar of
            retained earnings create at least a dollar of market value?
          </p>
        </Step>
        <Step n={5} title="Quality &amp; capital discipline + red flags: what could hurt me?">
          <p>
            Check debt (≤3 years of FCF is comfortable), stock compensation (≤15% of
            FCF), and sales efficiency (how much capital each new dollar of revenue
            requires). Then read each red flag — each one is a specific question to
            answer in the 10-K, linked at the bottom of the page.
          </p>
        </Step>
      </Card>

      {/* Workflow 2 */}
      <h2 className="text-base font-semibold tracking-tight mt-12">
        Workflow 2 — Find ideas without a stock tip
      </h2>
      <Card className="mt-3 p-5 space-y-5">
        <Step n={1} title="Start from a preset, not a blank filter">
          <p>
            Open the <Link href="/screener" className="text-accent hover:underline">screener</Link> and
            pick a preset that matches what you&apos;re hunting:{" "}
            <em>Quality compounders</em> (great businesses at any price),{" "}
            <em>Low expectations</em> (good businesses the market has given up on —
            implied growth ≤4%), or <em>Shareholder yield</em> (cash returners). The
            rules of every preset are printed above the table — nothing is hidden.
          </p>
        </Step>
        <Step n={2} title="Sort to sharpen">
          <p>
            Within a preset, click a column to sort. Example: in <em>Quality
            compounders</em>, sort by FCF yield descending — the top rows are the
            highest-quality businesses at the least demanding prices right now.
          </p>
        </Step>
        <Step n={3} title="Shortlist three, then run Workflow 1 on each">
          <p>
            The screener finds candidates, never answers. A stock that screens well
            can still have a broken story — that only shows up on the company page
            and in the filings.
          </p>
        </Step>
      </Card>

      {/* Workflow 3 */}
      <h2 className="text-base font-semibold tracking-tight mt-12">
        Workflow 3 — Choose between rivals
      </h2>
      <Card className="mt-3 p-5 space-y-5">
        <Step n={1} title="Compare trajectories, not sizes">
          <p>
            Open{" "}
            <Link href="/compare?tickers=V,MA,AXP" className="text-accent hover:underline">
              Compare with V, MA, AXP
            </Link>
            . Everything is indexed to 100 at the common start year, so a $500B company
            and a $100B company are judged on the same axis: who compounds faster.
          </p>
        </Step>
        <Step n={2} title="Check who grows cheaply">
          <p>
            The sales-efficiency table shows the capital cost of growth — dollars of
            new plant and equipment per dollar of new revenue. Under $0.50 is
            capital-light; a climb toward $1+ (as with the AI-datacenter builders
            recently) means growth is getting expensive to buy.
          </p>
        </Step>
        <Step n={3} title="Let the reverse DCF break the tie">
          <p>
            When two businesses are comparably good, open each in the{" "}
            <Link href="/tools/reverse-dcf" className="text-accent hover:underline">reverse DCF tool</Link>{" "}
            and compare implied growth against each one&apos;s history. Prefer the one
            where the market is asking for less.
          </p>
        </Step>
      </Card>

      <Card className="mt-10 p-5 bg-black/[0.02]">
        <p className="text-sm font-semibold">Habits that make the tool work</p>
        <ul className="mt-2 text-sm text-muted space-y-1.5 list-disc pl-5 leading-relaxed">
          <li>Read the 10-year record before the price. Deciding quality first keeps the valuation honest.</li>
          <li>Treat every flag and score as a question, not a conclusion — the answer lives in the 10-K.</li>
          <li>Compare yields to the risk-free alternative: a 2% FCF yield has to out-grow a ~4% Treasury by a lot.</li>
          <li>Missing data is information: “—” often means the metric doesn&apos;t apply (banks), not that it&apos;s zero.</li>
          <li>Revisit quarterly, not daily. Fundamentals move at 10-K speed.</li>
        </ul>
      </Card>

      <p className="mt-8 text-sm text-muted">
        Deeper material: the{" "}
        <Link href="/learn" className="text-accent hover:underline">metric reference and guides</Link>{" "}
        cover every formula on the site.
      </p>
    </div>
  );
}
